blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/yourusername/ViceMCP/discussions
    about: Please ask and answer questions here.
  - name: VICE Documentation
    url: https://vice-emu.sourceforge.io/
    about: For VICE-specific questions, see the official documentation.
  - name: MCP Documentation
    url: https://modelcontextprotocol.io/
    about: For MCP protocol questions, see the official documentation.