name: PR Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write
  checks: write

jobs:
  validate-pr:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
          deps
        requireScope: false
        subjectPattern: ^(?![A-Z]).+$
        subjectPatternError: |
          The subject "{subject}" found in the pull request title "{title}"
          didn't match the configured pattern. Please ensure that the subject
          doesn't start with an uppercase character.

    - name: Label PR
      uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

    - name: Check PR size
      uses: CodelyTV/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: '10'
        s_label: 'size/s'
        s_max_size: '100'
        m_label: 'size/m'
        m_max_size: '500'
        l_label: 'size/l'
        l_max_size: '1000'
        xl_label: 'size/xl'
        fail_if_xl: false

    - name: Welcome first-time contributors
      uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          Welcome @${{ github.actor }}! 👋
          
          Thank you for your contribution to ViceMCP! This appears to be your first pull request.
          
          Please make sure you've:
          - Read our [Contributing Guidelines](CONTRIBUTING.md)
          - Added tests for your changes
          - Updated documentation if needed
          
          A maintainer will review your PR soon. In the meantime, please ensure all CI checks pass.

  # Reviewer assignment disabled until repository has collaborators
  # assign-reviewers:
  #   name: Assign Reviewers
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.draft == false
  #   
  #   steps:
  #   - name: Auto-assign reviewers
  #     uses: kentaro-m/auto-assign-action@v2.0.0
  #     with:
  #       configuration-path: '.github/auto-assign.yml'